### ISSUE TITLE
src/index.md is read-only

### ISSUE THREAD

**Issue by blegat** [tlienart/JuDocTemplates.jl#22] opened 2019-10-11 09:14 UTC
I just run `newsite("blegat")` and the `index.md` and `config.md` are read-only, is that expected ?
```
$ ll
total 40K
drwxr-xr-x 5 blegat users 4.0K Oct 11 11:10 assets
drwxr-xr-x 2 blegat users 4.0K Oct 11 11:10 css
-rw-r--r-- 1 blegat users 2.1K Oct 11 11:10 feed.xml
-rw-r--r-- 1 blegat users  14K Oct 11 11:10 index.html
drwxr-xr-x 4 blegat users 4.0K Oct 11 11:09 libs
drwxr-xr-x 2 blegat users 4.0K Oct 11 11:10 pub
drwxr-xr-x 5 blegat users 4.0K Oct 11 11:09 src
$ cd src 
$ ll
total 28K
-r--r--r-- 1 blegat users  780 Oct 11 11:09 config.md
drwxr-xr-x 2 blegat users 4.0K Oct 11 11:09 _css
drwxr-xr-x 2 blegat users 4.0K Oct 11 11:09 _html_parts
-r--r--r-- 1 blegat users 8.3K Oct 11 11:09 index.md
drwxr-xr-x 2 blegat users 4.0K Oct 11 11:09 pages
```
I would expect to have `-rw...` instead of `-r-...` for `index.md` and `config.md`.

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by tlienart** [comment] 2019-10-11 09:29
Ah crap, no, I had an issue with this a short while back and tried to nuke it chmoding everything but it looks like the issue is still there.

Apologies for that and thanks for reporting, I'll try to fix it asap

**Comment by blegat** [comment] 2019-10-11 09:39
JoDoc v0.3.4 and JuDocTemplates master also work.

**Comment by tlienart** [comment] 2019-10-11 09:41
Yeah `newsite` is provided by JuDocTemplates so the JuDoc version doesn't matter. 

I still need to investigate though, I'm baffled this happened in the first place; since `newsite` copies a bunch of files maybe I did something silly there. 

Anyway thanks for reporting and glad it's working!

**Comment by tlienart** [comment] 2019-10-11 09:46
Btw, a bunch of bug fixes accumulated and are pending release 0.3.5 so for now you're probably best on `JuDoc#master` anyway 😄

**Comment by blegat** [comment] 2019-10-11 10:20
It seems that Julia creates files with different access rights when doing `] add` or `] dev`
```
$ ll -R /home/blegat/.julia/dev/JuDocTemplates
...
/home/blegat/.julia/dev/JuDocTemplates/src/templates/vela/src/_html_parts:
total 8.0K
-rw-r--r-- 1 blegat users  316 Oct 11 11:36 foot.html
-rw-r--r-- 1 blegat users 1.5K Oct 11 11:36 head.html
$ ll -R /home/blegat/.julia/packages/JuDocTemplates/C6jgR
...
/home/blegat/.julia/packages/JuDocTemplates/C6jgR/src/templates/vela/src/_html_parts:
total 8.0K
-r--r--r-- 1 blegat users  316 Oct 11 11:01 foot.html
-r--r--r-- 1 blegat users 1.5K Oct 11 11:01 head.html
```

**Comment by tlienart** [comment] 2019-10-11 10:24
Thanks for that and that also explains why I didn't see it; I guess I can just squeeze a `chmod` in the `newsite` function to make sure... trying this now

**Comment by tlienart** [comment] 2019-10-11 10:35
Ok I think this is fixed now. I'll tag a release in a minute.

I tried activating a new environment and

```
] add JuDoc JuDocTemplates#master
newsite("blah")
```

the perms are now 644. 

Thanks again for the heads up!

**Closed by tlienart** 2019-10-11 10:35 UTC
